import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import { createRequire } from "module";

const require = createRequire(import.meta.url);
const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const markdownItResolver = {
	name: 'markdownItResolver',
	setup(build) {
		build.onResolve({ filter: /^markdown-it\/lib\// }, args => {
			try {
				const result = require.resolve(args.path + '.mjs', { paths: [args.resolveDir] });
				return { path: result };
			} catch (e) {
				return null;
			}
		})
	},
}

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	plugins: [markdownItResolver],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	watch: !prod,
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	minify: prod,
	minifyWhitespace: prod,
	minifyIdentifiers: prod,
	minifySyntax: prod,
	outfile: 'dist/main.js',
}).catch(() => process.exit(1));
